### ISSUE TITLE
Result to a numpy / panda frame?

### ISSUE THREAD

**Issue by jjkoehorst** [ssciwr/hammingdist#134]
I could not find it in the documentation but what is the best / most efficient way of transforming the object to a panda or numpy dataframe? Currently writing the file to disk and loading it again but there might be a better way?

Thanks a lot for the extremely fast program!

**Comment by lkeegan** [comment]
@jjkoehorst with version 1.3.0 you should be able to directly access the distances as a 1-d numpy array
```
data = hammingdist.from_fasta("example.fasta")
lt_array = data.lt_array
```
The elements in this array are in lower-triangular order, i.e. correspond to the 2-d indices (row=1,col=0), (row=2,col=0), (row=2,col=1), ...
These indices can be generated using the numpy [tril_indices](https://numpy.org/doc/stable/reference/generated/numpy.tril_indices.html) function, e.g. to construct the lower-triangular distances matrix from the 1-d lt_array:
```
lt_matrix = np.zeros((n_seq, n_seq))
lt_matrix[np.tril_indices(n_seq, -1)] = lt_array
```
Hopefully that is helpful, free to re-open this issue if not.
