### ISSUE TITLE
Build Python package with OpenMP

### ISSUE THREAD

**Issue by dokempf** [ssciwr/hammingdist#17]
After a short followup discussion with Lukas: The type of experiments that will be carried out next does not involve ensembles, so multithreading the distance calculations would give a huge benefit. Building the Python package with OpenMP support should be easy. The only remaining question to me is, whether we want to provide threading control from within the Python package or ask them to manually set `OMP_NUM_THREADS`.

**Comment by lkeegan** [comment]
I'd probably go with `OMP_NUM_THREADS` - the RAM usage shouldn't increase with the number of threads, so the default of using all available cores is likely the desired behaviour in most cases (HPC or running locally)
